#!/bin/bash
# Generate config.h from config.env for ESP32 compilation

set -e

CONFIG_FILE="config.env"
OUTPUT_FILE="src/config.h"

# Check if config.env exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: $CONFIG_FILE not found!"
    exit 1
fi

# Load configuration from config.env
source "$CONFIG_FILE"

# Auto-detect local IP if not set
if [ -z "$MQTT_BROKER_IP" ]; then
    echo "Auto-detecting local IP address..."

    # Try to get the primary network interface IP (macOS/Linux)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS - get IP from en0 (WiFi) or en1 (Ethernet)
        MQTT_BROKER_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "")
    else
        # Linux - get IP from primary interface
        MQTT_BROKER_IP=$(hostname -I | awk '{print $1}')
    fi

    if [ -z "$MQTT_BROKER_IP" ]; then
        echo "ERROR: Could not auto-detect IP address!"
        echo "Please set MQTT_BROKER_IP in $CONFIG_FILE manually"
        exit 1
    fi

    echo "Detected IP: $MQTT_BROKER_IP"
fi

# Generate config.h
echo "Generating $OUTPUT_FILE..."

cat > "$OUTPUT_FILE" << EOF
// Auto-generated configuration file
// Generated at: $(date)
// Source: $CONFIG_FILE
// DO NOT EDIT THIS FILE MANUALLY - Edit $CONFIG_FILE instead

#ifndef CONFIG_H
#define CONFIG_H

// WiFi Configuration
#define WIFI_SSID "$WIFI_SSID"
#define WIFI_PASSWORD "$WIFI_PASSWORD"

// MQTT Configuration
#define MQTT_SERVER "$MQTT_BROKER_IP"
#define MQTT_PORT $MQTT_PORT
#define MQTT_CLIENT_ID "ESP32_Feuermelder"
#define MQTT_USER "$MQTT_USER"
#define MQTT_PASSWORD "$MQTT_PASSWORD"

// MQTT Topics
#define TOPIC_SENSORS "home/sensors/data"
#define TOPIC_STATUS "home/sensors/status"
#define TOPIC_CONTROL_RATE "home/sensors/control/rate"
#define TOPIC_CONTROL_ENABLE "home/sensors/control/enable"
#define TOPIC_CONTROL_BUZZER "home/sensors/control/buzzer"
#define TOPIC_CONTROL_LED "home/sensors/control/led"

#endif // CONFIG_H
EOF

echo "✓ Configuration generated successfully!"
echo "  MQTT Broker: $MQTT_BROKER_IP:$MQTT_PORT"
echo "  WiFi SSID: $WIFI_SSID"