# Feuermelder - Start All Services (Windows PowerShell)
# Complete native Windows implementation

$ErrorActionPreference = "Stop"

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  Feuermelder - Fire Detection System" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# Load configuration
if (-not (Test-Path "config.env")) {
    Write-Host "ERROR: config.env not found!" -ForegroundColor Red
    Write-Host "Please create config.env from the template" -ForegroundColor Yellow
    exit 1
}

# Parse config.env
$config = @{}
Get-Content "config.env" | ForEach-Object {
    $line = $_.Trim()
    if ($line -and -not $line.StartsWith("#")) {
        if ($line -match "^([^=]+)=(.*)$") {
            $key = $matches[1].Trim()
            $value = $matches[2].Trim() -replace '^"','' -replace '"$',''
            $config[$key] = $value
        }
    }
}

# Generate config.h for ESP32
Write-Host "Generating ESP32 configuration..." -ForegroundColor Yellow

# Auto-detect local IP if not set
$MQTT_BROKER_IP = $config["MQTT_BROKER_IP"]
if (-not $MQTT_BROKER_IP) {
    $ip = Get-NetIPAddress -AddressFamily IPv4 |
          Where-Object { $_.InterfaceAlias -notlike "*Loopback*" -and ($_.PrefixOrigin -eq "Dhcp" -or $_.PrefixOrigin -eq "Manual") } |
          Select-Object -First 1 -ExpandProperty IPAddress

    if (-not $ip) {
        $ip = Get-NetIPAddress -AddressFamily IPv4 |
              Where-Object { $_.IPAddress -ne "127.0.0.1" } |
              Select-Object -First 1 -ExpandProperty IPAddress
    }

    if (-not $ip) {
        $MQTT_BROKER_IP = "localhost"
    } else {
        $MQTT_BROKER_IP = $ip
    }
}

# Generate config.h
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$configH = @"
// Auto-generated configuration file
// Generated at: $timestamp
// Source: config.env
// DO NOT EDIT THIS FILE MANUALLY - Edit config.env instead

#ifndef CONFIG_H
#define CONFIG_H

// WiFi Configuration
#define WIFI_SSID "$($config["WIFI_SSID"])"
#define WIFI_PASSWORD "$($config["WIFI_PASSWORD"])"

// MQTT Configuration
#define MQTT_SERVER "$MQTT_BROKER_IP"
#define MQTT_PORT $($config["MQTT_PORT"])
#define MQTT_CLIENT_ID "ESP32_Feuermelder"
#define MQTT_USER "$($config["MQTT_USER"])"
#define MQTT_PASSWORD "$($config["MQTT_PASSWORD"])"

// MQTT Topics
#define TOPIC_SENSORS "home/sensors/data"
#define TOPIC_STATUS "home/sensors/status"
#define TOPIC_CONTROL_RATE "home/sensors/control/rate"
#define TOPIC_CONTROL_ENABLE "home/sensors/control/enable"
#define TOPIC_CONTROL_BUZZER "home/sensors/control/buzzer"
#define TOPIC_CONTROL_LED "home/sensors/control/led"

#endif // CONFIG_H
"@

Set-Content -Path "src/config.h" -Value $configH -Encoding UTF8
Write-Host ""

# Kill any existing Mosquitto processes
Get-Process mosquitto -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Seconds 1

# Check if Node.js is installed
$nodeInstalled = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeInstalled) {
    Write-Host "ERROR: Node.js is not installed!" -ForegroundColor Red
    Write-Host "Please install Node.js from: https://nodejs.org/" -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

# Check if Mosquitto is installed
$mosquittoInstalled = Get-Command mosquitto -ErrorAction SilentlyContinue
if (-not $mosquittoInstalled) {
    Write-Host "ERROR: Mosquitto is not installed!" -ForegroundColor Red
    Write-Host "Please install Mosquitto from: https://mosquitto.org/download/" -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

# Setup cleanup handler
$cleanup = {
    Write-Host ""
    Write-Host "Stopping services..." -ForegroundColor Yellow
    Get-Process mosquitto -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    exit 0
}

# Register cleanup on Ctrl+C
[Console]::TreatControlCAsInput = $false
$null = Register-EngineEvent -SourceIdentifier PowerShell.Exiting -Action $cleanup

# Start Mosquitto in background
Write-Host "Starting Mosquitto MQTT Broker..." -ForegroundColor Yellow
$mosquittoProcess = Start-Process -FilePath "mosquitto" -ArgumentList "-c", "mqtt/config/mosquitto.conf" -PassThru -NoNewWindow -RedirectStandardOutput "nul" -RedirectStandardError "nul"

# Wait for Mosquitto to start
Start-Sleep -Seconds 3

# Install web dependencies if needed
if (-not (Test-Path "web/node_modules")) {
    Write-Host "Installing web dependencies..." -ForegroundColor Yellow
    Push-Location web
    npm install
    Pop-Location
    Write-Host ""
}

# HTTPS Setup
$ENABLE_HTTPS = $false
$CERT_PATH = ""
$KEY_PATH = ""

if (-not (Test-Path "web/certs/cert.pem") -or -not (Test-Path "web/certs/key.pem")) {
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host "  HTTPS Certificate Setup" -ForegroundColor Cyan
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "No SSL certificates found. Would you like to:" -ForegroundColor Yellow
    Write-Host "1) Generate self-signed certificate (local/testing)"
    Write-Host "2) Skip and use HTTP only"
    Write-Host ""

    $https_choice = Read-Host "Enter choice [1-2] (default: 2)"
    if ([string]::IsNullOrWhiteSpace($https_choice)) {
        $https_choice = "2"
    }

    if ($https_choice -eq "1") {
        Write-Host "Generating self-signed certificate..." -ForegroundColor Yellow
        New-Item -Path "web/certs" -ItemType Directory -Force | Out-Null

        $opensslInstalled = Get-Command openssl -ErrorAction SilentlyContinue
        if ($opensslInstalled) {
            try {
                & openssl req -x509 -newkey rsa:2048 -nodes `
                    -keyout "web/certs/key.pem" `
                    -out "web/certs/cert.pem" `
                    -days 365 `
                    -subj "/C=DE/ST=NRW/L=Bielefeld/O=Feuermelder/CN=localhost" 2>$null

                if ($LASTEXITCODE -eq 0) {
                    Write-Host "Self-signed certificate generated" -ForegroundColor Green
                    $ENABLE_HTTPS = $true
                    $CERT_PATH = (Resolve-Path "web/certs/cert.pem").Path
                    $KEY_PATH = (Resolve-Path "web/certs/key.pem").Path
                } else {
                    Write-Host "Failed to generate certificate, using HTTP" -ForegroundColor Red
                    $ENABLE_HTTPS = $false
                }
            } catch {
                Write-Host "Failed to generate certificate, using HTTP" -ForegroundColor Red
                $ENABLE_HTTPS = $false
            }
        } else {
            Write-Host "OpenSSL not found, using HTTP" -ForegroundColor Red
            Write-Host "Install OpenSSL from: https://slproweb.com/products/Win32OpenSSL.html" -ForegroundColor Yellow
            $ENABLE_HTTPS = $false
        }
        Write-Host ""
    } else {
        Write-Host "Using HTTP only" -ForegroundColor Yellow
        $ENABLE_HTTPS = $false
        Write-Host ""
    }
} else {
    # Certificates exist, enable HTTPS
    $ENABLE_HTTPS = $true
    $CERT_PATH = (Resolve-Path "web/certs/cert.pem").Path
    $KEY_PATH = (Resolve-Path "web/certs/key.pem").Path
}

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  Services Started!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Cyan
$WEB_SERVER_PORT = if ($config["WEB_SERVER_PORT"]) { $config["WEB_SERVER_PORT"] } else { "3000" }
Write-Host "  - MQTT Broker: ${MQTT_BROKER_IP}:$($config["MQTT_PORT"])"
if ($ENABLE_HTTPS) {
    Write-Host "  - Web Server: https://localhost:${WEB_SERVER_PORT}" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Self-signed certificate warning is normal" -ForegroundColor Yellow
    Write-Host "  Click 'Advanced' -> 'Proceed to localhost' in browser" -ForegroundColor Yellow
} else {
    Write-Host "  - Web Server: http://localhost:${WEB_SERVER_PORT}" -ForegroundColor Green
}
Write-Host ""
Write-Host "  Configure ESP32 to connect to: ${MQTT_BROKER_IP}:$($config["MQTT_PORT"])"
Write-Host "  (Config will be embedded during PlatformIO build)"
Write-Host ""
Write-Host "  Press Ctrl+C to stop all services" -ForegroundColor Yellow
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# Export environment variables for web server
$env:MQTT_BROKER = $MQTT_BROKER_IP
$env:MQTT_PORT = $config["MQTT_PORT"]
$env:MQTT_USER = $config["MQTT_USER"]
$env:MQTT_PASSWORD = $config["MQTT_PASSWORD"]
$env:PORT = $WEB_SERVER_PORT
$env:ENABLE_HTTPS = $ENABLE_HTTPS.ToString().ToLower()
if ($ENABLE_HTTPS) {
    $env:CERT_PATH = $CERT_PATH
    $env:KEY_PATH = $KEY_PATH
}

# Start the web server (foreground)
try {
    Push-Location web
    & node src/server.js
} finally {
    Pop-Location
    & $cleanup
}